### PR TITLE
Feature/create test compatibility biosimulators for first example in sbml test suite

### PR DESCRIPTION
**Pull request by stellaprins**
See #49 

This PR is dependend on (and contains) the changes from PR #50

### CODE REVIEW

**Comment by stellaprins** [comment]
addresses #46 and part of #53 (non-omv-remote.yml and non-omv-local.yml)

**Comment by stellaprins** [comment]
Issue with `Testing non OMV scripts (remotely via URLs) / build (3.9) (pull_request)` (see [here](https://github.com/OpenSourceBrain/SBMLShowcase/actions/runs/11030458552/job/30636676554?pr=51)) after adding a minor change to the descriptions of the local and remote non-omv workflows (see [here](https://github.com/OpenSourceBrain/SBMLShowcase/pull/51/commits/0f8917fe09a4310d2f7745b28743bfc71e70d875))

**Comment by robertvi** [comment]
In download_file_from_link you return False if the download fails, whereas it should throw an exception. Otherwise the False is passed into shutil.unpack_archive as the filepath, which is what is generating the test error

**Comment by stellaprins** [comment]
@robertvi and I identified and resolved the bug that was causing the issue. We also added a try-except block for `HTTPError`, ensuring that the code continues even if a download fails.

**Review by robertvi — APPROVED** [review]

**Pull request merged**
