### PR TITLE
Feature/31 create lems nml2 ex9 fn docker results table

### PR DESCRIPTION
**Pull request by stellaprins**

### CODE REVIEW

**Comment by stellaprins** [comment]
- correct engines_dict for OpenCOR 
- merge dev into feature/31 branch

**Comment by pgleeson** [comment]
As discused, ARC can use the development branch as your staging post for stable updates. @stellaprins do set @robertvi as the suggested reviewer on this if it's ready for him to check and then open a PR to master with one of us assigned if it's ready for us to check.

**Review by robertvi — COMMENTED** [review]
Maybe hook this into GH actions testing in the same way as test_biosimulators_docker.py?

**Comment by robertvi** [comment]
Screenshot (440)

I am now getting the same error as the github action: the reason is that the files outputted from the model running in docker are set to be owned by root therefore the script does not have permission to move or delete them after the model finishes running

**Comment by robertvi** [comment]
added some code in the biosimulators_core functions that tries to change the file ownership of the docker output folder from root back to the user; I tried telling docker to run as the user instead of root but that caused the simulations to fail

**Comment by robertvi** [comment]
moved the code to change owner of the outputs into the calling function, to avoid it being inside the try/except block, but it still seems to not work

**Comment by robertvi** [comment]
Seems to work now, part of the problem seems to be output from a previous push's tests or a previous test in the same push still be present under the "output" folder, and being owned by root still.

**Comment by robertvi** [comment]
I was running out of space on my local machine testing the script, because the docker container runs seemed to be leaving a new image on disk after each run. I cleared them using 'docker system prune --all --volumes'

**Pull request merged**
