### PR TITLE
Feat 2 pyproject toml and linter

### PR DESCRIPTION
**Pull request by stellaprins**

### CODE REVIEW

**Comment by pgleeson** [comment]
@stellaprins This is useful for applying consistent formatting to the python scripts. The formatting shouldn't really be applied to auto generated XML or python files though, or files taken verbatim from external resources. We can discuss in the meeting though.

**Comment by pgleeson** [comment]
I think tyhe main ones to ignore are in the Brian and NEURON folders. Basically anything you or Rob haven't added/updated should probably be left as is.

**Comment by pgleeson** [comment]
@stellaprins Looks like there's been over 5000 new files in a recent commit. Assume that wasn't intended. Wouldn't be good to get this integrated with development/main. It may even be best to remove the offending commit from the commit history..?

**Comment by stellaprins** [comment]
@pgleeson I'm working out whether I can fit the repo into the [UCL ARC recommended template](https://github.com/UCL-ARC/python-tooling?tab=readme-ov-file) for Python projects using cookiecutter and probably have accidentily commited some local files that should have been ignored by git!

**Comment by pgleeson** [comment]
Ok, great. Glad to see a nice comprehensive template for a full Python project at ARC. Note not everything there is probably required as this repo is not intended as a pip installable package, just whatever will make a cleaner simpler set of files.

**Pull request closed without merging**
